[project]
name = "ukpostcodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
dev-dependencies = [
    "pre-commit"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
